### ISSUE TITLE
Call to function "list" failed: the "list" function was deprecated in Terraform v0.12

### ISSUE THREAD

**Issue by anothermountaingirl** [PackagePortal/terraform-aws-fargate-cluster#6]
##  Input

module "fargate-cluster" {
  source            = "PackagePortal/fargate-cluster/aws"
  version           = "1.0.2"
  region            = var.region
  app_name          = "appname"
  az_count          = 2
  vpc_id            = var.vpc_id
  image_name        = "image_name"
  cpu_units         = 256
  ram_units         = 512
  task_group_family = "test-task-family"
  cidr_bit_offset   = 8
  container_port    = 3000
  https_enabled     = true
  environment = [
    {
      name : "TBD"
      value : "TBD"
    }
  ]
  env_name = var.env_letter
  //   cert_arn          = aws_acm_certificate.cert.arn
}

## Error
Error: Error in function call
│ 
│   on .terraform/modules/fargate-cluster/main.tf line 243, in resource "aws_ecs_service" "fargate":
│  243:     for_each = local.nat_enabled ? [] : list(1)
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.

**Comment by bjewkes** [comment]
Thanks for bringing this up - see #7 which should resolve this. Its an easy fix I forgot about 😅
